// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcytPu84eZw5lQS4UFMTcY1JJwxj0O1IQ',
    appId: '1:697791643309:web:5ec1ab6774f3c481c49024',
    messagingSenderId: '697791643309',
    projectId: 'chat-flash-7119e',
    authDomain: 'chat-flash-7119e.firebaseapp.com',
    storageBucket: 'chat-flash-7119e.appspot.com',
    measurementId: 'G-GZK66B6ZJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSVVrLq-pH9-zezk9_gIJCzM1tUzHc3-8',
    appId: '1:697791643309:android:3f1357d8ec31684ac49024',
    messagingSenderId: '697791643309',
    projectId: 'chat-flash-7119e',
    storageBucket: 'chat-flash-7119e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWddjjMp0cgClRlJ5fNZ4egIjx-bq6r0Q',
    appId: '1:697791643309:ios:51d4872dd7973273c49024',
    messagingSenderId: '697791643309',
    projectId: 'chat-flash-7119e',
    storageBucket: 'chat-flash-7119e.appspot.com',
    iosClientId: '697791643309-4kkftm47thd5i3rfchfcst375c00c3a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWddjjMp0cgClRlJ5fNZ4egIjx-bq6r0Q',
    appId: '1:697791643309:ios:51d4872dd7973273c49024',
    messagingSenderId: '697791643309',
    projectId: 'chat-flash-7119e',
    storageBucket: 'chat-flash-7119e.appspot.com',
    iosClientId: '697791643309-4kkftm47thd5i3rfchfcst375c00c3a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );
}
